import base64
lines = [
    "## PR Re-Review --- Morris | tech-dev-agents #227 --- STORY-738 (Round 3)",
    "",
    "**CI:** PASS | **Verdict:** REQUEST_CHANGES --- H-2 blocker STILL NOT FIXED",
    "",
    "### Fix Verification",
    "| Finding | Status | Evidence |",
    "|---------|--------|----------|",
    "| H-2: partial-gate documentation | **NOT FIXED** | feature-spec.md Sections 2.2 and 2.3 gate the GET/POST endpoints. Section 2.1 (needs_info() extension) has zero mention of gating. The changelog commit did not add this documentation. |",
    "",
    "### What Is Still Missing",
    "The feature-spec.md documents the asymmetry but does not explain it is intentional. Sections 2.2/2.3 explicitly gate retrieval endpoints. Section 2.1 (write path) is ungated. No prose explains why.",
    "",
    "### Required Action --- Exact Text to Add",
    "Add to `features/story-738-*/feature-spec.md` after Section 2.3:",
    "",
    "```",
    "### 2.3a Gating Strategy --- Intentional Asymmetry",
    "",
    "**Design decision:** The needs_info() service method (Section 2.1) is NOT gated by",
    "OPS_DISPATCH_NEEDS_INFO_ENABLED. The write path is always active. Only the retrieval",
    "paths (Sections 2.2 and 2.3) are gated.",
    "",
    "**Rationale:** Agents invoke POST /dispatch/needs-info/{story_id} to transition state ---",
    "an existing ungated operation. question_text is an additive extension. The NEW",
    "capabilities requiring a feature flag are operator UI features: reading questions (GET)",
    "and posting answers (POST). Agents are not blocked when the feature is disabled.",
    "",
    "**Operational implication:** With gate OFF --- question_text is written to DB but cannot",
    "be retrieved. With gate ON --- full question/answer flow available. This is intentional.",
    "```",
    "",
    "This is documentation only --- no code changes required.",
    "",
    "Dispatching follow-up now.",
    "",
    "*Review by Morris (Claude Code deep analysis) 2026-05-01*",
]
body = chr(10).join(lines)
print(base64.b64encode(body.encode()).decode())
