import pathlib, sys

BASE = pathlib.Path('/home/hermes/dev/hpi-gorillacommerce/tech-dev-agents/state/morris')

PR_TRACKER = (
    "# PR Tracker \xe2\x80\x94 Last Updated: 2026-05-02T20:30Z\n"
    "\n"
    "Open: 25 | Approved (pending merge): 5 | Request Changes: 13 | Ready to merge: 2 | Dispatched: 8\n"
    "\n"
    "## Open PRs\n"
    "\n"
    "### advertising-amazon\n"
    "\n"
    "| PR | Story | Title | CI | Review | Mergeable | Notes |\n"
    "|----|-------|-------|----|--------|-----------|-------|\n"
    "| #331 | STORY-822 | feat(STORY-822): Fix migration 047 DDL, auth gate, version bump | pass | APPROVED | CONFLICTING | Approved \xe2\x80\x94 Mark to merge after rebase |\n"
    "| #330 | STORY-648 | STORY-648: Claude-facing slim MCP at /claude/mcp | \xe2\x9c\x85 green | REQUEST_CHANGES | CONFLICTING | Needs: rebase, dev-tasks.md update, SEC-004 path fix |\n"
    "| #329 | STORY-322 | feat(STORY-322): Loader Health Dashboard | none | REQUEST_CHANGES | CONFLICTING | Contaminated (node_modules+gitlinks). STORY-824 dispatched. |\n"
    "| #328 | STORY-816 | feat(STORY-816): fix PR #322 \xe2\x80\x94 migration chain, rank_disparity | pass | REQUEST_CHANGES | CONFLICTING | CRITICAL UniqueConstraint expression. STORY-823 dispatched. |\n"
    "| #325 | STORY-642 | feat(STORY-642): BSR Gap Alerting \xe2\x80\x94 5 alert types, cooldown | pass | COMMENTED | CONFLICTING | Previous review was APPROVE_WITH_CONDITIONS \xe2\x80\x94 confirm PR #299 was properly reviewed |\n"
    "| #323 | STORY-641 | STORY-641: automated dispatch (medium scope) | \xe2\x80\x94 | APPROVED | CONFLICTING | C1/H1/H2 all fixed. Mark to merge after rebase. |\n"
    "| #322 | STORY-644 | feat(STORY-644): BSR competitor category misclassification | \xe2\x80\x94 | CONDITIONAL_APPROVE | CONFLICTING | Confirm snapshot_at column name + TC-11 follow-up required before feature launch. Close #328 first. |\n"
    "| #319 | STORY-640 | feat(STORY-640): Competitor set maintenance CRUD + editor | \xe2\x80\x94 | APPROVED | CONFLICTING | All showstoppers fixed. Mark to merge after rebase. |\n"
    "| #316 | answers/strategy | answers(strategy-2026): ad-team Q&A \xe2\x80\x94 partial | \xe2\x9c\x85 green | READY_TO_MERGE | MERGEABLE | Morris self-review: all 38 Qs decided. Update PR body then merge. |\n"
    "| #315 | STORY-094 | feat(STORY-094): cache-first SP keyword bids + batch sync | pass | REQUEST_CHANGES | CONFLICTING | H3: gitlink verification needed. STORY-825 dispatched. |\n"
    "| #314 | STORY-639 | feat(STORY-639): productize emergency budget recovery CLI | \xe2\x80\x94 | APPROVED | CONFLICTING | C1+C2 verified fixed. Mark to merge after rebase. |\n"
    "\n"
    "### tech-dev-agents\n"
    "\n"
    "| PR | Story | Title | CI | Review | Mergeable | Notes |\n"
    "|----|-------|-------|----|--------|-----------|-------|\n"
    "| #261 | STORY-795 | STORY-795: Rework fleet vigilance post-merge sweep | \xe2\x9d\x8c fail | REQUEST_CHANGES | CONFLICTING | B1: seed.md sections. B2: _validate_api_key() dead. H1/H2 git log parser + lookback gap. Rework dispatched. |\n"
    "| #260 | STORY-100 | feat(STORY-100): dispatch queue smoke tests | \xe2\x9d\x8c fail | REQUEST_CHANGES | CONFLICTING | B1: seed.md sections. B2: rebase. Rework dispatched. |\n"
    "| #259 | STORY-096 | feat(STORY-096): queue smoke tests for pre-deploy gate | \xe2\x9d\x8c fail | REQUEST_CHANGES | CONFLICTING | CRITICAL: force_claim() deleted + rework_of removed from fallback. Rework dispatched. |\n"
    "| #258 | STORY-095 | feat(STORY-095): dispatch queue smoke tests | \xe2\x9d\x8c fail | REQUEST_CHANGES | CONFLICTING | B1: seed.md sections. B2: rebase. Rework dispatched. |\n"
    "| #257 | STORY-803 | feat(STORY-803): fix needs_info loop | \xe2\x9d\x8c fail | REQUEST_CHANGES | CONFLICTING | CI failures + seed.md sections + unrelated debris. Rework dispatched. |\n"
    "| #256 | STORY-802 | feat(STORY-802): drive Foundry spend \xe2\x89\xa4$20/day | \xe2\x80\x94 | REQUEST_CHANGES | CONFLICTING | query_cost_alerts missing; scope confusion; bundled stories. Rework dispatched. |\n"
    "| #250 | STORY-800 | feat(STORY-800): Fleet Vigilance Check 17 (rework #244) | \xe2\x80\x94 | REQUEST_CHANGES | CONFLICTING | HIGH: re-enqueue logic inside per-merge loop. Rework dispatched. |\n"
    "| #235 | STORY-774 | STORY-774: Dashboard logout clears all auth state | \xe2\x80\x94 | REQUEST_CHANGES | CONFLICTING | HIGH: No CI checks ran. Rework dispatched. |\n"
    "\n"
    "### tech-gc-knowledgebase\n"
    "\n"
    "| PR | Story | Title | CI | Review | Mergeable | Notes |\n"
    "|----|-------|-------|----|--------|-----------|-------|\n"
    "| #71 | STORY-814 | STORY-814: Research AWS Autonomous Cloud Coding Agents | \xe2\x80\x94 | APPROVED | CONFLICTING | STORY-830 dispatched to rebase |\n"
    "| #70 | STORY-812 | STORY-812: Research Stripe Minions one-shot coding agents | \xe2\x80\x94 | APPROVED | CONFLICTING | STORY-829 dispatched to rebase |\n"
    "| #68 | STORY-811 | STORY-811: Research Gastown framework | \xe2\x80\x94 | APPROVED | CONFLICTING | STORY-828 dispatched to rebase |\n"
    "| #67 | STORY-810 | STORY-810: Research Cline Kanban | \xe2\x80\x94 | APPROVED | CONFLICTING | STORY-827 dispatched to rebase. Merge in order: #67\xe2\x86\x92#68\xe2\x86\x92#70\xe2\x86\x92#71 |\n"
    "| #64 | STORY-765 | feat(STORY-765): Shipping Address & Customer Location Data | \xe2\x80\x94 | REQUEST_CHANGES | CONFLICTING | B-1: phantom file. B-2: ads-research/ dir structure. STORY-826 dispatched. |\n"
    "\n"
    "### gc-infra\n"
    "\n"
    "| PR | Title | CI | Review | Mergeable | Notes |\n"
    "|----|-------|----|--------|-----------|-------|\n"
    "| #1 | feat: Terramate scaffold + mise config + AWS bootstrap | \xe2\x9d\x8c 7 fail | REQUEST_CHANGES | MERGEABLE | BLOCKER: module source paths not updated after modules/\xe2\x86\x92tf-modules/ rename. Human author (jduarte-buildstr). |\n"
    "\n"
    "### sdlc-framework\n"
    "\n"
    "| PR | Title | CI | Review | Mergeable | Notes |\n"
    "|----|-------|----|--------|-----------|-------|\n"
    "| #1 | retro: apply 14 findings from project retrospective | \xe2\x80\x94 | APPROVED (2026-04-20) | CONFLICTING | 38 days old. Rebase nudge posted. Author: markoreta-gc. |\n"
    "\n"
    "## Dispatch Summary (2026-05-02 session)\n"
    "\n"
    "| Story | Rework of | Repo | Queue depth | Notes |\n"
    "|-------|-----------|------|-------------|-------|\n"
    "| STORY-823 | STORY-816 | advertising-amazon | 24 | PR #328 UniqueConstraint fix + TC-11 |\n"
    "| STORY-824 | STORY-322 | advertising-amazon | 25 | PR #329 decontaminate branch |\n"
    "| STORY-825 | STORY-094 | advertising-amazon | 26 | PR #315 gitlink verification |\n"
    "| STORY-826 | STORY-765 | tech-gc-knowledgebase | 27 | PR #64 phantom file + dir structure |\n"
    "| STORY-827 | STORY-810 | tech-gc-knowledgebase | 28 | PR #67 rebase |\n"
    "| STORY-828 | STORY-811 | tech-gc-knowledgebase | 29 | PR #68 rebase |\n"
    "| STORY-829 | STORY-812 | tech-gc-knowledgebase | 30 | PR #70 rebase |\n"
    "| STORY-830 | STORY-814 | tech-gc-knowledgebase | 31 | PR #71 rebase |\n"
)

(BASE / 'pr-tracker.md').write_text(PR_TRACKER)
print('pr-tracker.md written, size:', (BASE / 'pr-tracker.md').stat().st_size)
