#!/usr/bin/env bash
# update-baselines.sh — Refresh Morris fleet metric baselines from Prometheus.
#
# STORY-508 (AC-8): Queries Prometheus for current P50/P95 latency percentiles
# and writes updated baselines to /home/hermes/state/morris/metrics-baselines.md.
#
# Run: manually or via cron (e.g., every Sunday 02:00 UTC: 0 2 * * 0)
# Deployed to /opt/agent/scripts/update-baselines.sh on Morris VM.
#
# Requires:
#   PROMETHEUS_URL — Prometheus endpoint (default: http://prometheus.gorillacommerce.ai:9090)
#   PROMETHEUS_TOKEN — Bearer token (optional, for authenticated Prometheus)
#
# Output: /home/hermes/state/morris/metrics-baselines.md (overwritten each run)

set -euo pipefail

PROMETHEUS_URL="${PROMETHEUS_URL:-http://prometheus.gorillacommerce.ai:9090}"
PROMETHEUS_TOKEN="${PROMETHEUS_TOKEN:-}"
BASELINES_FILE="/home/hermes/state/morris/metrics-baselines.md"
TS=$(date -u +%Y-%m-%dT%H:%M:%SZ)

echo "[$TS] update-baselines: querying Prometheus at $PROMETHEUS_URL"

# Helper: query Prometheus instant query API
prom_query() {
    local query="$1"
    local auth_header=""
    if [ -n "$PROMETHEUS_TOKEN" ]; then
        auth_header="-H \"Authorization: Bearer $PROMETHEUS_TOKEN\""
    fi
    curl -sf \
        ${PROMETHEUS_TOKEN:+-H "Authorization: Bearer $PROMETHEUS_TOKEN"} \
        "${PROMETHEUS_URL}/api/v1/query" \
        --data-urlencode "query=${query}" \
        | python3 -c "
import sys, json
d = json.load(sys.stdin)
results = d.get('data', {}).get('result', [])
if results:
    print(results[0]['value'][1])
else:
    print('N/A')
" 2>/dev/null || echo "N/A"
}

# --- P50 dispatch-to-complete latency (seconds) ---
# Uses histogram_quantile(0.50, ...) over the dispatch_duration_seconds histogram.
P50_SECONDS=$(prom_query 'histogram_quantile(0.50, rate(dispatch_duration_seconds_bucket[7d]))')
P95_SECONDS=$(prom_query 'histogram_quantile(0.95, rate(dispatch_duration_seconds_bucket[7d]))')

# --- Claim timeout rate ---
CLAIM_TIMEOUT_RATE=$(prom_query 'rate(dispatch_claim_timeouts_total[1h]) * 3600')

# --- Partial PR count ---
PARTIAL_PR_COUNT=$(prom_query 'sum(partial_pr_open_total) or vector(0)')

# --- Rate limit deferrals per hour ---
RATE_LIMIT_RATE=$(prom_query 'rate(dispatch_rate_limit_deferrals_total[1h]) * 3600')

# Format seconds to human-readable (Xh Ym)
format_duration() {
    local secs="${1:-N/A}"
    if [ "$secs" = "N/A" ]; then echo "N/A"; return; fi
    local isecs
    isecs=$(printf "%.0f" "$secs" 2>/dev/null || echo 0)
    local h=$(( isecs / 3600 ))
    local m=$(( (isecs % 3600) / 60 ))
    echo "${h}h ${m}m"
}

P50_HUMAN=$(format_duration "$P50_SECONDS")
P95_HUMAN=$(format_duration "$P95_SECONDS")

# Write updated baselines file
mkdir -p "$(dirname "$BASELINES_FILE")"
cat > "$BASELINES_FILE" <<EOF
# Morris Fleet Metric Baselines
<!-- Auto-generated by update-baselines.sh — do not edit manually -->
<!-- Last updated: $TS -->

## Dispatch Latency

| Percentile | Duration | Raw (seconds) |
|-----------|----------|---------------|
| P50 (median) | $P50_HUMAN | $P50_SECONDS |
| P95 | $P95_HUMAN | $P95_SECONDS |

## Claim Timeouts

- Claim timeout rate (per hour): **$CLAIM_TIMEOUT_RATE**

## Partial PRs

- Partial PRs currently open: **$PARTIAL_PR_COUNT**

## Rate Limit Deferrals

- Deferrals per hour (1h rate): **$RATE_LIMIT_RATE**

---
_Baselines are used by Grafana alert thresholds and the alert-handler skill._
_Source: Prometheus at $PROMETHEUS_URL_
EOF

echo "[$TS] update-baselines: baselines written to $BASELINES_FILE"
cat "$BASELINES_FILE"
