-- =============================================================================
-- Snowflake Schema & Role Setup
-- Run as SYSADMIN against YOUR_DATABASE
-- Replace YOUR_DATABASE and YOUR_WAREHOUSE with your actual values
-- =============================================================================

USE ROLE SYSADMIN;
USE DATABASE YOUR_DATABASE;

-- -----------------------------------------------------------------------------
-- Schemas
-- Standard dbt layered architecture: raw → staging → intermediate → marts
-- -----------------------------------------------------------------------------

CREATE SCHEMA IF NOT EXISTS RAW
  COMMENT = 'Raw data landed directly from S3 via COPY INTO. Never manually modified.';

CREATE SCHEMA IF NOT EXISTS STAGING
  COMMENT = 'dbt staging models — light cleaning, renaming, type casting. Prefix: stg_';

CREATE SCHEMA IF NOT EXISTS INTERMEDIATE
  COMMENT = 'dbt intermediate models — joins, aggregations, business logic. Prefix: int_';

CREATE SCHEMA IF NOT EXISTS MARTS
  COMMENT = 'dbt mart models — facts and dimensions for consumption. Prefix: fct_ dim_';

CREATE SCHEMA IF NOT EXISTS NEO_DEV
  COMMENT = 'Neo implementation sandbox. Not for production use.';

CREATE SCHEMA IF NOT EXISTS SMITH_TEST
  COMMENT = 'Agent Smith validation schema for data quality checks.';

-- -----------------------------------------------------------------------------
-- Roles
-- -----------------------------------------------------------------------------

CREATE ROLE IF NOT EXISTS AGENT_LOADER
  COMMENT = 'Loads raw data from S3 into RAW schema via COPY INTO';

CREATE ROLE IF NOT EXISTS AGENT_TRANSFORMER
  COMMENT = 'dbt transformations — reads RAW, writes STAGING / INTERMEDIATE / MARTS';

CREATE ROLE IF NOT EXISTS AGENT_ANALYST
  COMMENT = 'Read-only access to MARTS for validation and reporting';

-- Warehouse access
GRANT USAGE ON WAREHOUSE YOUR_WAREHOUSE TO ROLE AGENT_LOADER;
GRANT USAGE ON WAREHOUSE YOUR_WAREHOUSE TO ROLE AGENT_TRANSFORMER;
GRANT USAGE ON WAREHOUSE YOUR_WAREHOUSE TO ROLE AGENT_ANALYST;

-- Database access
GRANT USAGE ON DATABASE YOUR_DATABASE TO ROLE AGENT_LOADER;
GRANT USAGE ON DATABASE YOUR_DATABASE TO ROLE AGENT_TRANSFORMER;
GRANT USAGE ON DATABASE YOUR_DATABASE TO ROLE AGENT_ANALYST;

-- -----------------------------------------------------------------------------
-- AGENT_LOADER grants (RAW schema only — write access for ingestion)
-- -----------------------------------------------------------------------------

GRANT USAGE ON SCHEMA RAW TO ROLE AGENT_LOADER;
GRANT CREATE TABLE ON SCHEMA RAW TO ROLE AGENT_LOADER;
GRANT INSERT, UPDATE, SELECT ON ALL TABLES IN SCHEMA RAW TO ROLE AGENT_LOADER;
GRANT INSERT, UPDATE, SELECT ON FUTURE TABLES IN SCHEMA RAW TO ROLE AGENT_LOADER;
GRANT CREATE STAGE ON SCHEMA RAW TO ROLE AGENT_LOADER;

-- -----------------------------------------------------------------------------
-- AGENT_TRANSFORMER grants (read RAW, write STAGING/INTERMEDIATE/MARTS/NEO_DEV)
-- -----------------------------------------------------------------------------

GRANT USAGE ON SCHEMA RAW TO ROLE AGENT_TRANSFORMER;
GRANT SELECT ON ALL TABLES IN SCHEMA RAW TO ROLE AGENT_TRANSFORMER;
GRANT SELECT ON FUTURE TABLES IN SCHEMA RAW TO ROLE AGENT_TRANSFORMER;

GRANT USAGE ON SCHEMA STAGING TO ROLE AGENT_TRANSFORMER;
GRANT CREATE TABLE, CREATE VIEW ON SCHEMA STAGING TO ROLE AGENT_TRANSFORMER;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA STAGING TO ROLE AGENT_TRANSFORMER;
GRANT SELECT, INSERT, UPDATE, DELETE ON FUTURE TABLES IN SCHEMA STAGING TO ROLE AGENT_TRANSFORMER;

GRANT USAGE ON SCHEMA INTERMEDIATE TO ROLE AGENT_TRANSFORMER;
GRANT CREATE TABLE, CREATE VIEW ON SCHEMA INTERMEDIATE TO ROLE AGENT_TRANSFORMER;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA INTERMEDIATE TO ROLE AGENT_TRANSFORMER;
GRANT SELECT, INSERT, UPDATE, DELETE ON FUTURE TABLES IN SCHEMA INTERMEDIATE TO ROLE AGENT_TRANSFORMER;

GRANT USAGE ON SCHEMA MARTS TO ROLE AGENT_TRANSFORMER;
GRANT CREATE TABLE, CREATE VIEW ON SCHEMA MARTS TO ROLE AGENT_TRANSFORMER;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA MARTS TO ROLE AGENT_TRANSFORMER;
GRANT SELECT, INSERT, UPDATE, DELETE ON FUTURE TABLES IN SCHEMA MARTS TO ROLE AGENT_TRANSFORMER;

GRANT USAGE ON SCHEMA NEO_DEV TO ROLE AGENT_TRANSFORMER;
GRANT CREATE TABLE, CREATE VIEW ON SCHEMA NEO_DEV TO ROLE AGENT_TRANSFORMER;
GRANT ALL ON ALL TABLES IN SCHEMA NEO_DEV TO ROLE AGENT_TRANSFORMER;
GRANT ALL ON FUTURE TABLES IN SCHEMA NEO_DEV TO ROLE AGENT_TRANSFORMER;

-- -----------------------------------------------------------------------------
-- AGENT_ANALYST grants (read MARTS + SMITH_TEST for validation)
-- -----------------------------------------------------------------------------

GRANT USAGE ON SCHEMA MARTS TO ROLE AGENT_ANALYST;
GRANT SELECT ON ALL TABLES IN SCHEMA MARTS TO ROLE AGENT_ANALYST;
GRANT SELECT ON FUTURE TABLES IN SCHEMA MARTS TO ROLE AGENT_ANALYST;
GRANT SELECT ON ALL VIEWS IN SCHEMA MARTS TO ROLE AGENT_ANALYST;
GRANT SELECT ON FUTURE VIEWS IN SCHEMA MARTS TO ROLE AGENT_ANALYST;

GRANT USAGE ON SCHEMA STAGING TO ROLE AGENT_ANALYST;
GRANT SELECT ON ALL TABLES IN SCHEMA STAGING TO ROLE AGENT_ANALYST;
GRANT SELECT ON FUTURE TABLES IN SCHEMA STAGING TO ROLE AGENT_ANALYST;

GRANT USAGE ON SCHEMA SMITH_TEST TO ROLE AGENT_ANALYST;
GRANT ALL ON ALL TABLES IN SCHEMA SMITH_TEST TO ROLE AGENT_ANALYST;
GRANT ALL ON FUTURE TABLES IN SCHEMA SMITH_TEST TO ROLE AGENT_ANALYST;

-- -----------------------------------------------------------------------------
-- Assign all roles to dbt_user
-- -----------------------------------------------------------------------------

GRANT ROLE AGENT_LOADER      TO USER dbt_user;
GRANT ROLE AGENT_TRANSFORMER TO USER dbt_user;
GRANT ROLE AGENT_ANALYST     TO USER dbt_user;

-- Set default role (transformer is the primary dbt role)
ALTER USER dbt_user SET DEFAULT_ROLE = AGENT_TRANSFORMER;

-- Register RSA public key (run after generating key pair per infra/README.md)
-- ALTER USER dbt_user SET RSA_PUBLIC_KEY = 'YOUR_PUBLIC_KEY_WITHOUT_HEADER_FOOTER';
